<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="9.0.7" />
    <PackageReference Include="Prism.DryIoc" Version="9.0.537" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Data\TeamManager.db">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="License.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Service\" />
  </ItemGroup>
</Project>